all:
	@echo.
	g++ -o 1.class.exe 1.class.cpp
	./1.class.exe
	@echo.

	@echo.
	g++ -o 2.destructor.exe 2.destructor.cpp
	./2.destructor.exe
	@echo.

	@echo.
	g++ -o 3.tiposAccesoClases.exe 3.tiposAccesoClases.cpp
	./3.tiposAccesoClases.exe
	@echo.

	@echo.
	g++ -o 4.objetosEnFunciones.exe 4.objetosEnFunciones.cpp
	./4.objetosEnFunciones.exe
	@echo.

	@echo.
	g++ -o 5.retornarObjetos.exe 5.retornarObjetos.cpp
	./5.retornarObjetos.exe
	@echo.

	@echo.
	g++ -o 6.separandoArchivos.exe 6.separandoArchivos/personas.cpp 6.separandoArchivos/main.cpp
	./6.separandoArchivos.exe
	@echo.

	@echo.
	g++ -o 7.ejercicioConvertir.exe 7.ejercicioConvertir/estudiante.cpp 7.ejercicioConvertir/main.cpp
	./7.ejercicioConvertir.exe
	@echo.

	@echo.
	g++ -o 8.sobrecargaOperadores.exe 8.sobrecargaOperadores.cpp 
	./8.sobrecargaOperadores.exe
	@echo.

	@echo.
	g++ -o 9.herencia.exe 9.herencia.cpp 
	./9.herencia.exe
	@echo.

	@echo.
	g++ -o 10.sobreescrituraHerencia.exe 10.sobreescrituraHerencia.cpp 
	./10.sobreescrituraHerencia.exe
	@echo.

	@echo.
	g++ -o 11.miembrosProtegidos.exe 11.miembrosProtegidos.cpp 
	./11.miembrosProtegidos.exe
	@echo.

	@echo.
	g++ -o 12.multinivelHerencia.exe 12.multinivelHerencia.cpp 
	./12.multinivelHerencia.exe
	@echo.

	@echo.
	g++ -o 13.multipleHerencia.exe 13.multipleHerencia.cpp 
	./13.multipleHerencia.exe
	@echo.

	@echo.
	g++ -o 15.funcionesClasesAmigas_1.exe 15.funcionesClasesAmigas_1.cpp 
	./15.funcionesClasesAmigas_1.exe
	@echo.

	@echo.
	g++ -o 16.funcionesClasesAmigas_2.exe 16.funcionesClasesAmigas_2.cpp 
	./16.funcionesClasesAmigas_2.exe
	@echo.

	@echo.
	g++ -o 17.funcionesClasesAmigas_3.exe 17.funcionesClasesAmigas_3.cpp 
	./17.funcionesClasesAmigas_3.exe
	@echo.

	@echo.
	g++ -o 18.funcionesVirtuales.exe 18.funcionesVirtuales.cpp 
	./18.funcionesVirtuales.exe
	@echo.

