all:
	@echo.
	g++ -o 1.bubbleSort.exe 1.bubbleSort.cpp
	./1.bubbleSort.exe
	@echo.

	@echo.
	g++ -o 2.bubbleSortOptimizado.exe 2.bubbleSortOptimizado.cpp
	./2.bubbleSortOptimizado.exe
	@echo.

	@echo.
	g++ -o 3.selectionSort.exe 3.selectionSort.cpp
	./3.selectionSort.exe
	@echo.

	@echo.
	g++ -o 4.insertionSort.exe 4.insertionSort.cpp
	./4.insertionSort.exe
	@echo.

	@echo.
	g++ -o 5.quickSort.exe 5.quickSort.cpp
	./5.quickSort.exe
	@echo.