all:
	@echo.
	@g++ -o 1.functionTemplate.exe 1.functionTemplate.cpp
	@echo Function template:
	@./1.functionTemplate.exe
	@echo.

	@echo.
	@g++ -o 2.classTemplate.exe 2.classTemplate.cpp
	@echo Class template:
	@./2.classTemplate.exe
	@echo.

	@echo.
	@g++ -o 3.dosParametrosTemplate.exe 3.dosParametrosTemplate.cpp
	@echo Dos Parametros template:
	@./3.dosParametrosTemplate.exe
	@echo.

	@echo.
	@g++ -o 4.tresParametrosTemplate.exe 4.tresParametrosTemplate.cpp
	@echo Tres Parametros template:
	@./4.tresParametrosTemplate.exe
	@echo.

	@echo.
	@g++ -o 5.excepciones.exe 5.excepciones.cpp
	@echo Excepciones:
	@./5.excepciones.exe
	@echo.

	@echo.
	@g++ -o 6.multipleExceptions.exe 6.multipleExceptions.cpp
	@echo multiples excepciones:
	@./6.multipleExceptions.exe
	@echo.

	@echo.
	@g++ -o 7.noExceptionVersusException.exe 7.noExceptionVersusException.cpp
	@echo No Excepcion VS Excepcion:
	@./7.noExceptionVersusException.exe
	@echo.

