all: 
	@echo.
	g++ 1.helloWorld.cpp -o 1.helloWorld.exe
	./1.helloWorld.exe
	@echo.

	@echo.
	g++ 2.variables.cpp -o 2.variables.exe
	./2.variables.exe
	@echo.

	@echo.
	g++ 3.variables2.cpp -o 3.variables2.exe
	./3.variables2.exe
	@echo.

	@echo.
	g++ 4.cinYcout.cpp -o 4.cinYcout.exe
	./4.cinYcout.exe
	@echo.	

	@echo.
	g++ 5.string.cpp -o 5.string.exe
	./5.string.exe
	@echo.	

	@echo.
	g++ 6.condiciones.cpp -o 6.condiciones.exe
	./6.condiciones.exe
	@echo.	

	@echo.
	g++ 7.loops.cpp -o 7.loops.exe
	./7.loops.exe
	@echo.	

	@echo.
	g++ 8.breakContinua.cpp -o 8.breakContinua.exe
	./8.breakContinua.exe
	@echo.	

	@echo.
	g++ 9.array.cpp -o 9.array.exe
	./9.array.exe
	@echo.	

	@echo.
	g++ 10.funcion.cpp -o 10.funcion.exe  
	./10.funcion.exe 
	@echo.

	@echo.
	g++ 11.sobreFuncion.cpp -o  11.sobreFuncion.exe
	./11.sobreFuncion.exe
	@echo.

	@echo.
	g++ 12.variablesContinuacion.cpp 12.variablesContinuacion2.cpp -o  12.variablesContinuacion.exe    
	./12.variablesContinuacion.exe
	@echo.

	@echo.
	g++ 13.estructuras.cpp -o 13.estructuras.exe   
	./13.estructuras.exe  
	@echo.
