all:
	@echo.
	g++ -o 1.memoriaProgramas.exe 1.memoriaProgramas.cpp
	./1.memoriaProgramas.exe
	@echo.

	@echo.
	g++ -o 2.memoriaDinamica_1.exe 2.memoriaDinamica_1.cpp
	./2.memoriaDinamica_1.exe
	@echo.

	@echo.
	g++ -o 2.memoriaDinamica_2.exe 2.memoriaDinamica_2.cpp
	./2.memoriaDinamica_2.exe
	@echo.

	@echo.
	g++ -o 2.memoriaDinamica_3.exe 2.memoriaDinamica_3.cpp
	./2.memoriaDinamica_3.exe
	@echo.

	@echo.
	g++ -o 3.memoriaDinamicaMalloc.exe 3.memoriaDinamicaMalloc.cpp
	./3.memoriaDinamicaMalloc.exe
	@echo.

	@echo.
	g++ -o 3.memoriaDinamicaCalloc.exe 3.memoriaDinamicaCalloc.cpp
	./3.memoriaDinamicaCalloc.exe
	@echo.

	@echo.
	g++ -o 3.memoriaDinamicaRealloc.exe 3.memoriaDinamicaRealloc.cpp
	./3.memoriaDinamicaRealloc.exe
	@echo.
	
	@echo.
	g++ -o 4.estructuraDatos.exe 4.estructuraDatos.cpp
	./4.estructuraDatos.exe
	@echo.
	
	@echo.
	g++ -o 5.colaEstructuraDatos.exe 5.colaEstructuraDatos.cpp
	./5.colaEstructuraDatos.exe
	@echo.

	@echo.
	g++ -o 6.listaEnlazadaEstructuraDatos.exe 6.listaEnlazadaEstructuraDatos.cpp
	./6.listaEnlazadaEstructuraDatos.exe
	@echo.

	@echo.
	g++ -o 7.arbolEstructuraDatos.exe 7.arbolEstructuraDatos.cpp
	./7.arbolEstructuraDatos.exe
	@echo.