all:
	@echo.
	g++ -o 1.sum.exe 1.2sum.cpp 1.1main.cpp
	./1.sum.exe
	@echo.

	@echo.
	g++ -o 2.typeCasting.exe 2.typeCasting.cpp
	./2.typeCasting.exe
	@echo.

	@echo.
	g++ -o 3.goTo.exe 3.goTo.cpp
	./3.goTo.exe
	@echo.

	@echo.
	g++ -o 4.recursividad.exe 4.recursividad.cpp
	./4.recursividad.exe
	@echo.

	@echo.
	g++ -o 5.enumeraciones.exe 5.enumeraciones.cpp
	./5.enumeraciones.exe
	@echo.

	@echo.
	g++ -o 6.defines.exe 6.defines.cpp
	./6.defines
	@echo.

	@echo.
	g++ -o 7.memoryMap.exe 7.memoryMap.cpp
	./7.memoryMap.exe 
	@echo.

	@echo.
	g++ -o 8.punteros.exe 8.punteros.cpp
	./8.punteros.exe
	@echo.

	@echo.
	g++ -o 9.punterosEstructuras.exe 9.punterosEstructuras.cpp
	./9.punterosEstructuras.exe
	@echo.

	@echo.
	g++ -o 10.punterosArreglos.exe 10.punterosArreglos.cpp
	./10.punterosArreglos.exe
	@echo.

	@echo.
	g++ -o 11.punterosFunciones.exe 11.punterosFunciones.cpp
	./11.punterosFunciones.exe
	@echo.