all:
	@echo.
	@echo Programa: 1.hello.py
	@py 1.hello.py
	@echo.

	@echo.
	@echo Programa: 2.comentarios.py
	@py 2.comentarios.py
	@echo.

	@echo.
	@echo Programa: 3.variablesContantesLiterales.py
	@py 3.variablesContantesLiterales.py
	@echo.

	@echo.
	@echo Programa: 4.tiposDatos.py
	@py 4.tiposDatos.py
	@echo.

	@echo.
	@echo Programa: 5.conversionesDatos.py
	@py 5.conversionesDatos.py
	@echo.

	@echo.
	@echo Programa: 6.salidas.py
	@py 6.salidas.py
	@echo.