all:

	@echo.
	@g++ -o motocoche.exe MotoCoche.cpp Vehiculo.cpp Moto.cpp Coche.cpp main.cpp
	@echo "Ejercicio de POO"
	@./motocoche.exe
	@echo.

	@echo.
	@g++ -o dinamica.exe dinamica.cpp
	@echo "Ejercicio de memoria dinámica"
	@./dinamica.exe
	@echo.

