all:
	@echo.
	@g++ -o 1.containersVector.exe 1.containersVector.cpp
	@echo Containers de sencuencia:
	@./1.containersVector.exe
	@echo.

	@echo.
	@g++ -o 2.containersSet.exe 2.containersSet.cpp
	@echo Containers asociativos:
	@./2.containersSet.exe
	@echo.

	@echo.
	@g++ -o 3.containersUnorderedSet.exe 3.containersUnorderedSet.cpp
	@echo Containers asociativos desordenados:
	@./3.containersUnorderedSet.exe
	@echo.

	@echo.
	@g++ -o 4.cointainersMap.exe 4.cointainersMap.cpp
	@echo Containers usando MAP:
	@./4.cointainersMap.exe
	@echo.

	@echo.
	@g++ -o 5.containersAdapters.exe 5.containersAdapters.cpp
	@echo Containers Adapters:
	@./5.containersAdapters.exe
	@echo.

	@echo.
	@g++ -o 6.iterators.exe 6.iterators.cpp
	@echo Iteradores:
	@./6.iterators.exe
	@echo.

	@echo.
	@g++ -o 7.inputAndOutputiterator.exe 7.inputAndOutputiterator.cpp
	@echo Iteradores de Entrada y Salida:
	@./7.inputAndOutputiterator.exe
	@echo.

	@echo.
	@g++ -o 8.forwardIterator.exe 8.forwardIterator.cpp
	@echo Iterador Forward:
	@./8.forwardIterator.exe
	@echo.

	@echo.
	@g++ -o 9.bidirectionalIterator.exe 9.bidirectionalIterator.cpp
	@echo Iterador Bidireccional:
	@./9.bidirectionalIterator.exe
	@echo.

	@echo.
	@g++ -o 10.randomAccessIterator.exe 10.randomAccessIterator.cpp
	@echo Iterador de Acceso Aleatorio:
	@./10.randomAccessIterator.exe
	@echo.

	@echo.
	@g++ -o 11.algoritmos.exe 11.algoritmos.cpp
	@echo Algoritmos:
	@./11.algoritmos.exe
	@echo.